# Generated by Django 5.0.6 on 2024-05-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytable',
            name='field10',
        ),
        migrations.RemoveField(
            model_name='mytable',
            name='field11',
        ),
        migrations.RemoveField(
            model_name='mytable',
            name='field12',
        ),
        migrations.RemoveField(
            model_name='mytable',
            name='field13',
        ),
        migrations.RemoveField(
            model_name='mytable',
            name='field4',
        ),
        migrations.RemoveField(
            model_name='mytable',
            name='field5',
        ),
        migrations.RemoveField(
            model_name='mytable',
            name='field6',
        ),
        migrations.RemoveField(
            model_name='mytable',
            name='field7',
        ),
        migrations.RemoveField(
            model_name='mytable',
            name='field8',
        ),
        migrations.RemoveField(
            model_name='mytable',
            name='field9',
        ),
        migrations.AlterField(
            model_name='mytable',
            name='field1',
            field=models.CharField(default='USER', max_length=100),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='field2',
            field=models.CharField(default='NAME', max_length=100),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='field3',
            field=models.CharField(default='DEP', max_length=10),
        ),
    ]
