# Generated by Django 5.0.6 on 2024-05-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_mytable_field10_remove_mytable_field11_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytable',
            old_name='field2',
            new_name='Apelido',
        ),
        migrations.RenameField(
            model_name='mytable',
            old_name='field1',
            new_name='Nome',
        ),
        migrations.RemoveField(
            model_name='mytable',
            name='field3',
        ),
        migrations.AddField(
            model_name='mytable',
            name='Departamento',
            field=models.CharField(default='DEP', max_length=100),
        ),
    ]
