# Generated by Django 5.0.6 on 2024-05-14 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_field2_mytable_apelido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytable',
            name='Ano',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mytable',
            name='DirUni',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='FaltaInjust',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='FaltaJust',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Func',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Grupo',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='mytable',
            name='NumAvali',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='NumColab',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Pin',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Apelido',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Departamento',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Nome',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
